name: dinov2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - torchvision=0.15.0
  - torchmetrics=0.10.3
  - omegaconf
  - fvcore
  - iopath
  - mkl=2024.0.0
  - numpy==1.24.4
  - conda-forge::opencv=4.7.0
  - pip
  - pip:
      - --extra-index-url https://pypi.nvidia.com
      - cuml-cu11